### ISSUE TITLE
Crashes when object is null

### ISSUE THREAD

**Issue by saravanaj** [jonsequitur/dotnet-repl#11]
First of all: great work! Absolutely loving it.

**Repro:**

```csharp
C# > string s = null;
C# > s
```

Crashes the entire process with the exception:

```
Unhandled exception: System.InvalidOperationException: Sequence contains no elements
   at System.Linq.ThrowHelper.ThrowNoElementsException()
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source)
   at dotnet_repl.AnsiConsoleExtensions.GetMarkup(DisplayEvent event) in C:\dev\dotnet-repl\src\dotnet-repl\AnsiConsoleExtensions.cs:line 132
   at dotnet_repl.AnsiConsoleExtensions.GetSuccessDisplay(DisplayEvent event, KernelSpecificTheme theme, String header) in C:\dev\dotnet-repl\src\dotnet-repl\AnsiConsoleExtensions.cs:line 76
   at dotnet_repl.Repl.<>c__DisplayClass27_1.<RunKernelCommand>b__3(KernelEvent event) in C:\dev\dotnet-repl\src\dotnet-repl\Repl.cs:line 244
   at System.Reactive.AnonymousObserver`1.OnNextCore(T value) in /_/Rx.NET/Source/src/System.Reactive/AnonymousObserver.cs:line 67
   at System.Reactive.ObserverBase`1.OnNext(T value) in /_/Rx.NET/Source/src/System.Reactive/ObserverBase.cs:line 34
   at System.Reactive.Subjects.FastImmediateObserver`1.EnsureActive(Int32 count) in /_/Rx.NET/Source/src/System.Reactive/Subjects/ReplaySubject.cs:line 863
   at System.Reactive.Subjects.ReplaySubject`1.ReplayBase.Subscribe(IObserver`1 observer) in /_/Rx.NET/Source/src/System.Reactive/Subjects/ReplaySubject.cs:line 395
   at System.Reactive.Subjects.ReplaySubject`1.Subscribe(IObserver`1 observer) in /_/Rx.NET/Source/src/System.Reactive/Subjects/ReplaySubject.cs:line 200
   at System.ObservableExtensions.SubscribeSafe[T](IObservable`1 source, IObserver`1 observer) in /_/Rx.NET/Source/src/System.Reactive/Observable.Extensions.cs:line 395
--- End of stack trace from previous location ---
   at System.Reactive.PlatformServices.ExceptionServicesImpl.Rethrow(Exception exception) in /_/Rx.NET/Source/src/System.Reactive/Internal/ExceptionServicesImpl.cs:line 19
   at System.Reactive.ExceptionHelpers.Throw(Exception exception) in /_/Rx.NET/Source/src/System.Reactive/Internal/ExceptionServices.cs:line 16
   at System.Reactive.Stubs.<>c.<.cctor>b__2_1(Exception ex) in /_/Rx.NET/Source/src/System.Reactive/Internal/Stubs.cs:line 16
   at System.Reactive.AnonymousObserver`1.OnErrorCore(Exception error) in /_/Rx.NET/Source/src/System.Reactive/AnonymousObserver.cs:line 73
   at System.Reactive.ObserverBase`1.OnError(Exception error) in /_/Rx.NET/Source/src/System.Reactive/ObserverBase.cs:line 59
   at System.ObservableExtensions.SubscribeSafe[T](IObservable`1 source, IObserver`1 observer) in /_/Rx.NET/Source/src/System.Reactive/Observable.Extensions.cs:line 421
   at System.Reactive.Subjects.ConnectableObservable`2.Subscribe(IObserver`1 observer) in /_/Rx.NET/Source/src/System.Reactive/Subjects/ConnectableObservable.cs:line 90
   at System.ObservableExtensions.Subscribe[T](IObservable`1 source, Action`1 onNext) in /_/Rx.NET/Source/src/System.Reactive/Observable.Extensions.cs:line 63
   at dotnet_repl.Repl.<>c__DisplayClass27_0.<<RunKernelCommand>b__1>d.MoveNext() in C:\dev\dotnet-repl\src\dotnet-repl\Repl.cs:line 193
--- End of stack trace from previous location ---
   at Spectre.Console.LiveDisplay.<>c__DisplayClass17_0.<<StartAsync>b__0>d.MoveNext() in /_/src/Spectre.Console/Widgets/Live/LiveDisplay.cs:line 84
--- End of stack trace from previous location ---
   at Spectre.Console.LiveDisplay.<>c__DisplayClass18_0`1.<<StartAsync>b__0>d.MoveNext() in /_/src/Spectre.Console/Widgets/Live/LiveDisplay.cs:line 114
--- End of stack trace from previous location ---
   at Spectre.Console.Internal.DefaultExclusivityMode.Run[T](Func`1 func) in /_/src/Spectre.Console/Internal/DefaultExclusivityMode.cs:line 49
   at Spectre.Console.LiveDisplay.StartAsync[T](Func`2 func) in /_/src/Spectre.Console/Widgets/Live/LiveDisplay.cs:line 102
   at Spectre.Console.LiveDisplay.StartAsync(Func`2 func) in /_/src/Spectre.Console/Widgets/Live/LiveDisplay.cs:line 82
   at dotnet_repl.Repl.RunKernelCommand(KernelCommand command) in C:\dev\dotnet-repl\src\dotnet-repl\Repl.cs:line 189
   at dotnet_repl.Repl.RunAsync(NotebookDocument notebook, Boolean exitAfterRun) in C:\dev\dotnet-repl\src\dotnet-repl\Repl.cs:line 127
   at dotnet_repl.CommandLineParser.StartRepl(StartupOptions options, CancellationToken cancellationToken, IAnsiConsole ansiConsole) in C:\dev\dotnet-repl\src\dotnet-repl\CommandLineParser.cs:line 106
   at System.CommandLine.Invocation.CommandHandler.GetExitCodeAsync(Object value, InvocationContext context)
   at System.CommandLine.Invocation.ModelBindingCommandHandler.InvokeAsync(InvocationContext context)
   at System.CommandLine.Invocation.InvocationPipeline.<>c__DisplayClass4_0.<<BuildInvocationChain>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass23_0.<<UseParseErrorReporting>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass16_0.<<UseHelp>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass27_0.<<UseVersionOption>b__1>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass25_0.<<UseTypoCorrections>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<UseSuggestDirective>b__24_0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass22_0.<<UseParseDirective>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass11_0.<<UseDebugDirective>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<RegisterWithDotnetSuggest>b__10_0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass14_0.<<UseExceptionHandler>b__0>d.MoveNext()
```

**Comment by jonsequitur** [comment]
Well that's embarrassing!

Thanks for the bug report!
